# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            The Data Guide
tagline:          'Community data guide'
description:      "MPCA's community guide to finding data"
url:              https://MPCA-data.github.io/Data-Guide/
baseurl:          /Data-Guide/

toc:
  max_level: 2 # default: 6

author:
  name:           'MPCA'
  url:            https://twitter.com/mnpca

paginate:         3

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/mpca-data/Data-Guide
